# App server
server:
  port: 8090

# Spring Application
spring:
  application:
    name: api-gateway-ms
  #secrity
#  security:
#    user:
#      name: kd
#      password: kd
  # cloud
  cloud:
    gateway:
      routes:
           # company MS
        - id: company-service
          uri: lb://COMPANYMICROSERVICE
          predicates:
            - Path=/company/**
          # job MS
        - id: job-service
          uri: lb://JOBMICROSERVICE
          predicates:
            - Path=/job/**
          # eureka server
        - id: eureka-server
          uri: http://localhost:8761
          predicates:
            - Path=/eureka/main
          filters:
            - SetPath=/
            # for the css of eureka server
        - id: eureka-server-static
          uri: http://localhost:8761
          predicates:
            - Path=/eureka/**

# Eureka Client Configuration
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    register-with-eureka: true
    fetch-registry: true

# Zipkin Tracing
management:
  tracing:
    sampling:
      probability: 1.0

# Logging Configuration
logging:
  level:
    root: info
    org.springframework.cloud.gateway.route.RouteDefinitionLocator: INFO
    org.springframework.cloud.gateway: TRACE