spring:
  main:
   web-application-type: reactive
   allow-bean-definition-overriding: true
  # app name
  application:
    name: CompanyMicroService
  # Mongo DB
  data:
    mongodb:
      database: MicroServiceDB
      auto-index-creation: true
      uri: mongodb+srv://knightkrish:rmtDzoQ5nk7aCwX9@cluster0.jepfx.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0spring.data.mongodb.auto-index-creation=true
      authentication-database: admin
      host: localhost
      port: 27017
  rabbitmq:
    host: localhost
    port: 5672
    username: kd
    password: kd


#  security:
#    user:
#      name: kd
#      password: kd

#Eureka
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
    register-with-eureka: true
    fetch-registry: true

server:
  port: 8091

# Zipkin Tracing
management:
  tracing:
    sampling:
      probability: 1.0
  #Actuator ( to access it -> localhost:8091/actuator/health )
  health:
    circuitbreakers:
          enabled: true
  endpoints:
    web:
      exposure:
         include: health
  endpoint:
    health:
      show-details: always


# Resilience4j
resilience4j:
  circuitbreaker:
    instances:
      #name of the instance
      companyBreaker:
        #circuit breaker
        registerHealthIndicator: true
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        permittedNumberOfCallsInHalfOpenState: 3
        waitDurationInOpenState: 10s
        failureRateThreshold: 50
        register-health-indicator: true
        automatic-transition-from-open-to-half-open-enabled: true
        sliding-window-type: count_based
        #Retry
        max-attempts: 5
        wait-duration: 2s
  # Rate limiter
  ratelimiter:
    instance:
      companyBreaker:
        timeout-duration: 0
        limit-refresh-period: 4
        limit-for-period: 2




                            #HardCode
FeignClient:
  Job:
    url: http://localhost:8092/job
  review:
    url: http://localhost:8093/reviews

feign:
 codec:
  enable-default=true: