spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/CompanyAppDB
    username: kd
    password: kd
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
     ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
  security:
    user:
      name: kd
      password: kd