spring:
  application:
    name: companyApp
  datasource:
    url: jdbc:postgresql://localhost:5432/CompanyAppDB
    username: kd
    password: kd
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
     ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
# config server
  config:
    import: optional:configserver:http://localhost:8080
  profiles:
    active: default
#  security:
#    user:
#      name: kd
#      password: kd

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
    register-with-eureka: true
    fetch-registry: true

server:
  port: 8091

#zipkin
management:
  tracing:
    sampling:
      probability: 1.0