spring:
  application:
    name: JobApp
  datasource:
    url: jdbc:postgresql://localhost:5432/JobAppDB
    username: kd
    password: kd
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
#  security:
#    user:
#      name: kd
#      password: kd

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
    register-with-eureka: true
    fetch-registry: true

server:
  port: 8092